### ISSUE TITLE
Could I use API directly in my app?

### ISSUE THREAD

**Issue by 0x241F31** [DurtyFree/GTA-SA-ScriptHook#3]
I would like to use api in my winform app, is it possible?

**Comment by 0x241F31** [comment]
like outside Script inheritance

**Comment by DarkIrata** [comment]
Hi, sorry for the late answer.
The Scripthook and the script files has to placed in the corresponding directory from the gta sa root directory. 
You would need to make a 2 part application. The WinForms and the script which is loaded by the scripthook and let them community through any kind of protocol. (Sockets, Pipelines, etc.)

**Comment by 0x241F31** [comment]
Thanks for an explanation!
